name: UI Tests — Login

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        default: 'chrome'
        type: choice
        options: ['chrome', 'firefox']

jobs:
  login-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      suite_name:   'Login'
      test_groups:  'login'
      thread_count: '1'
      browser:      ${{ inputs.browser || 'chrome' }}
      deploy_pages: false
    secrets:
      SAUCEDEMO_BASE_URL:     ${{ secrets.SAUCEDEMO_BASE_URL }}
      USER_STANDARD_USERNAME: ${{ secrets.USER_STANDARD_USERNAME }}
      USER_STANDARD_PASSWORD: ${{ secrets.USER_STANDARD_PASSWORD }}
      USER_LOCKED_USERNAME:   ${{ secrets.USER_LOCKED_USERNAME }}
      CHECKOUT_FIRSTNAME:     ${{ secrets.CHECKOUT_FIRSTNAME }}
      CHECKOUT_LASTNAME:      ${{ secrets.CHECKOUT_LASTNAME }}
      CHECKOUT_ZIPCODE:       ${{ secrets.CHECKOUT_ZIPCODE }}
